// All 300 lines are available to every role. A recognizable phrase must never
// identify a secret role. Decisions and context, not a role-exclusive vocabulary,
// determine what a computer player says. Lines are sampled without recent repeats.
export const DIALOGUE = {
  opening: [
    'Let us build a voting record before we build a conspiracy theory.',
    'First government, first impressions. I am watching the policy result.',
    'Everyone sounds trustworthy before the first red policy.',
    'A calm table is still allowed to be a suspicious table.',
    'I would like explanations that survive the next round.',
    'We have very little evidence. Let us admit that.',
    'I am keeping track of who backs which government.',
    'No instant heroes. No instant villains. Show me policies.',
    'The first election is a chance to learn something.',
    'Confidence is easy. A useful voting history takes work.',
    'I will reconsider my reads when the evidence changes.',
    'A persuasive speech does not change the policy deck.',
    'Let us hear the nomination before deciding the verdict.',
    'Trust is provisional at this table.',
    'I am more interested in consistent decisions than impressive speeches.',
    'Nobody has earned a permanent seat in government yet.',
    'An early result is a clue, not a complete solution.',
    'There are more fascist policies in the deck. Remember that.',
    'We need both policies and information from these elections.',
    'I am ready to be convinced, within reason.',
    'Let us not turn a random first presidency into evidence.',
    'I will judge the government after it has actually governed.',
    'We can disagree without ignoring the board.',
    'I expect a few confident claims and at least one bad theory.',
    'A good opening is a government we can learn from.',
    'I am listening for promises people will remember later.',
    'Keep your arguments specific. Names and decisions help.',
    'The interesting part is who changes their mind, and why.',
    'I want a record we can compare, not a volume contest.',
    'All right, chamber. Give me a reason to trust you.',
  ],
  nomination: [
    'This nomination should give us a useful result to evaluate.',
    'I want this pair to have a chance to govern.',
    'Let us test this partnership with an actual policy.',
    'I am willing to put this choice on the record.',
    'This is my best nomination with the information available.',
    'A new pairing might tell us more than another argument.',
    'I can defend this nomination. I cannot promise the draw.',
    'I want a chancellor whose choices we can examine afterward.',
    'The term limits leave us options. This is mine.',
    'Judge the pairing, then hold us to the result.',
    'This candidate deserves consideration before an automatic Nein.',
    'I am choosing a partner, not issuing a certificate of innocence.',
    'We need a government with a reasonable path to approval.',
    'I would rather nominate clearly than leave everyone guessing.',
    'My nomination is a proposal. Make your own judgment.',
    'There is enough here to try this government.',
    'This pairing is worth putting before the chamber.',
    'I am not asking for permanent trust, just a considered vote.',
    'I would like the next discussion to include a policy result.',
    'A nomination is not proof of shared allegiance.',
    'Let us see whether this combination can deliver.',
    'This is a deliberate choice, even with incomplete evidence.',
    'The chamber can decide whether my reasoning holds up.',
    'I prefer this candidate over the eligible alternatives.',
    'A government needs two seats. I am proposing this second one.',
    'I want this choice examined alongside the current tracker.',
    'There is no risk-free nominee. This is the risk I favor.',
    'I am giving this partnership a public test.',
    'We should get an answer from the ballot box now.',
    'I have made the nomination. Let us hear the objections.',
  ],
  yes: [
    'I am leaning Ja on this government.',
    'This pair clears my bar for an election.',
    'I would rather see this government act than reject it on instinct.',
    'I am prepared to give this pairing a chance.',
    'There is enough upside here for my support.',
    'My read favors approving this government.',
    'I can support this without pretending I know every role.',
    'A measured Ja seems reasonable here.',
    'I think this election is worth passing.',
    'I favor getting a policy result from this pair.',
    'I do not see enough reason to stop this government.',
    'I am willing to take this particular chance.',
    'Supporting a government does not mean trusting it forever.',
    'I would approve this and review the result carefully.',
    'The argument for trying this pair is stronger for me.',
    'My current preference is to let them govern.',
    'This looks like an acceptable election risk.',
    'I am not convinced that rejection improves our position.',
    'I want to learn what this government produces.',
    'The chamber needs to make progress. I favor this attempt.',
    'I am giving this proposal the benefit of a vote.',
    'This is support for one government, not a blank cheque.',
    'I think we have a workable pairing.',
    'The balance of what I know points toward Ja.',
    'I can live with testing this nomination.',
    'Approving this pair seems better than the alternatives right now.',
    'I am comfortable backing this election.',
    'I would like this government to get its chance.',
    'There is uncertainty, but uncertainty alone is not a veto.',
    'My preference is a passed election and a result to discuss.',
  ],
  no: [
    'I am leaning Nein on this pairing.',
    'I would prefer the next presidential candidate.',
    'This government has not earned my support.',
    'I see enough risk here to favor rejection.',
    'I am not sold on this nomination.',
    'I would like a different combination in government.',
    'My concern is the pairing, not how confidently it was announced.',
    'I think waiting for another proposal is justified.',
    'This election feels like the wrong chance to take.',
    'I need a stronger reason to approve these two.',
    'A confident nomination is still open to a Nein.',
    'I would rather spend an election failure than approve this blindly.',
    'I am keeping the tracker in mind, but I still have doubts.',
    'This proposal does not resolve my concerns.',
    'I am looking for a government with a better case.',
    'I cannot support every pair just to appear cooperative.',
    'There are other eligible candidates I would rather consider.',
    'My read is against this election.',
    'I think the chamber should ask for another proposal.',
    'I am not comfortable with this government yet.',
    'I see more reasons to withhold support than grant it.',
    'I do not want to reward an argument I do not believe.',
    'A rejection can be useful if we learn from the next nomination.',
    'I favor a change in the proposed government.',
    'This is a considered objection, not an automatic Nein.',
    'I want a pairing I can defend after the cards are played.',
    'The evidence has not moved me toward approval.',
    'I would not put my support behind this one.',
    'I am skeptical enough to oppose the proposal.',
    'Let us see whether the next nominee offers a better path.',
  ],
  liberal: [
    'A liberal policy is progress. It is not a complete role reveal.',
    'That blue policy gives the government some credit.',
    'Good result. I still want to compare the explanations.',
    'I am updating my read in light of that policy.',
    'The board has moved in a useful direction.',
    'One blue does not make a player permanently trustworthy.',
    'We have a result worth remembering at the next nomination.',
    'That government has a positive result on its record.',
    'Credit for the policy, caution about the conclusions.',
    'I would like to see whether this pattern continues.',
    'Useful progress, and another piece of public evidence.',
    'That result makes the next election discussion more interesting.',
    'We should record the success without declaring the case closed.',
    'A blue policy is a better argument than a loud speech.',
    'That is something concrete to weigh in future votes.',
    'I will remember who helped approve that government.',
    'Good outcomes matter, even when the reasoning was uncertain.',
    'This gives us a little more room to think.',
    'Do not confuse a helpful policy with guaranteed innocence.',
    'The policy count has improved. The deduction is still unfinished.',
    'That result earns attention at the next eligible nomination.',
    'A productive government is worth discussing carefully.',
    'I am giving the result some weight in my next decision.',
    'We now have more than just first impressions.',
    'It is possible to play blue for credibility. Keep comparing rounds.',
    'That was useful. Let us keep the standard of evidence consistent.',
    'A good policy should change our reads a little, not erase them.',
    'The board gives us a fact; the claims still need judgment.',
    'I want the chamber to remember this result accurately.',
    'Let us carry the progress into a sensible next government.',
  ],
  fascist: [
    'A red policy needs discussion, but it does not prove a red role.',
    'There are eleven fascist policies in the starting deck. Bad draws happen.',
    'I want to compare the government claims after that result.',
    'That policy increases the pressure on the next election.',
    'We should examine the result without inventing a hand we never saw.',
    'A forced draw and a deliberate choice can look identical from outside.',
    'I am more cautious about that government now.',
    'The board is getting less forgiving.',
    'That is a result we should keep in the public record.',
    'We need explanations, not an instant unanimous accusation.',
    'I want to know whether the two government stories agree.',
    'The red track has moved. Check what the new space means.',
    'Suspicion is reasonable; certainty would be premature.',
    'We cannot see discarded cards. Treat every claim accordingly.',
    'This is where a consistent voting record starts to matter.',
    'The government should expect questions about that outcome.',
    'Do not let a dramatic explanation replace evidence.',
    'A bad result is useful information, even when it is frustrating.',
    'I will weigh that policy in future nominations.',
    'We should distinguish what happened from what people say happened.',
    'That outcome gives us a reason to revisit our assumptions.',
    'I want a careful next government after that red policy.',
    'Nobody outside legislation knows exactly which choices were available.',
    'That is another step toward a dangerous board state.',
    'I am listening for contradictions between the two officials.',
    'Red policies can come from either unlucky cards or intentional choices.',
    'The explanation matters, but the policy is the verified fact.',
    'I would like more than a shrug from the last government.',
    'This result changes the stakes of our next vote.',
    'Let us use the evidence without pretending it is complete.',
  ],
  danger: [
    'At three fascist policies, the chancellor nomination can end the game.',
    'A chancellor election becomes much more dangerous after the third red.',
    'We must weigh Hitler risk alongside the policy record now.',
    'Being confirmed not Hitler does not confirm Liberal membership.',
    'Check the election tracker before rejecting another government.',
    'Three failed governments enact the top policy without a power.',
    'The chaos policy is not chosen by the proposed government.',
    'Do not sleepwalk into a decisive election.',
    'We need to think about the next turn as well as this one.',
    'The board can make a formerly reasonable nomination much riskier.',
    'Late elections deserve more scrutiny than opening guesses.',
    'A single government can settle this game under the right conditions.',
    'The policy count matters more than how comfortable the table feels.',
    'Term limits still matter when the stakes rise.',
    'A safe-looking conversation can lead to a dangerous ballot.',
    'Remember that a tie rejects the government.',
    'An enacted policy resets the tracker; merely winning a vote does not.',
    'The veto only unlocks after the fifth fascist policy.',
    'A veto requires both officials to agree.',
    'Agreeing to a veto also advances the election tracker.',
    'Rejecting a risky pair has a cost when chaos is close.',
    'The next policy may change which powers are available.',
    'A surviving chancellor election after three reds rules out Hitler.',
    'We need an argument suited to this board, not the opening board.',
    'The late game punishes careless assumptions.',
    'Look at both win conditions before settling on a candidate.',
    'Do not ignore a possible immediate win while debating old suspicions.',
    'Every living player still counts toward the voting majority.',
    'A failed government changes the rotation as well as the tracker.',
    'We should know exactly what our next decision risks.',
  ],
  investigation: [
    'An investigation reveals party membership, not the exact secret role.',
    'A Fascist membership result alone does not identify Hitler.',
    'Only the investigating president sees the actual result.',
    'An investigator can lie about what they saw.',
    'I want the investigation claim kept alongside the voting record.',
    'Choose an investigation target whose result will help future decisions.',
    'Information is useful only if we decide how much to trust its source.',
    'The chamber hears a claim, not the membership card itself.',
    'An investigation creates another story we can compare with behavior.',
    'We should remember who vouched for whom.',
    'A private result is not a public proof.',
    'I am interested in the choice of target as well as the claim.',
    'The investigator has an advantage, but the rest of us must still reason.',
    'We cannot investigate the same person again in this game.',
    'A useful investigation can shape several future nominations.',
    'Keep the distinction between membership and identity clear.',
    'The result is private; the responsibility for the claim is public.',
    'I want to see whether the investigator acts consistently afterward.',
    'An investigation is a tool, not permission to stop thinking.',
    'The claim should be tested against later choices.',
    'Investigating someone does not automatically make the investigator trustworthy.',
    'There may be more to learn from a contested seat than a comfortable one.',
    'We should not forget this investigation two rounds from now.',
    'The strongest claim still depends on whether its speaker is honest.',
    'A party check and a policy peek reveal different kinds of information.',
    'This is a good moment to separate confirmed facts from reported facts.',
    'The choice of investigation target deserves an explanation.',
    'Let us keep track of which seats have already been checked.',
    'I will compare that claim with the next government proposal.',
    'Information powers can help the table or help someone build a story.',
  ],
  execution: [
    'An execution is final. Make the target count.',
    'Executing Hitler ends the game immediately with a Liberal victory.',
    'A surviving game after execution does not reveal the target party.',
    'The president has to choose; the chamber can only argue its case.',
    'I want this decision based on more than the loudest accusation.',
    'A mistaken execution changes the voting numbers for everyone.',
    'Think about which outcome would most improve the position.',
    'Suspicion deserves explanation before it becomes a target.',
    'The choice of target will tell us something about the president too.',
    'Executed players lose their vote and must remain silent.',
    'This power is not an optional extra step.',
    'I am weighing the public record carefully here.',
    'A strong speech is not enough to make someone the right target.',
    'We should consider who benefits from each possible execution.',
    'Removing a player can make the next majority very different.',
    'The table should remember the reasoning behind this decision.',
    'Do not treat an execution that misses Hitler as proof of innocence.',
    'This is the point where a weak read has a permanent cost.',
    'There is no vote to undo the presidential decision.',
    'I want evidence weighed consistently across the possible targets.',
    'An executed non-Hitler keeps their party secret until the end.',
    'We need to think about the surviving table, too.',
    'A target should make sense in the current game, not an old argument.',
    'The president must choose another living player.',
    'This decision deserves a careful look at the last few rounds.',
    'Pressure can make a convenient target look like a convincing one.',
    'I will judge the execution alongside the rest of this presidency.',
    'If the game continues, we still have deduction work to do.',
    'An execution changes the table even when it does not settle the game.',
    'Let us make the reasoning clear before this power is used.',
  ],
  reply: [
    'I am comparing policy results and voting patterns, not just promises.',
    'I hear the argument. I am still weighing it against the board.',
    'That is possible, but it is not the only explanation.',
    'I would like to see that claim match the next decision.',
    'Which public result makes that theory stronger?',
    'I can change my read if the evidence improves.',
    'We should separate what we know from what we suspect.',
    'I would not call anyone cleared on that argument alone.',
    'A contradiction is useful; a confident accusation is not enough.',
    'My opinion is still provisional.',
    'I am not ignoring the claim. I am deciding how much weight it deserves.',
    'The next nomination may tell us more than another round of certainty.',
    'I want to compare both officials before settling on a theory.',
    'It is fair to ask for a reason behind a vote.',
    'There is a difference between a plausible story and a verified fact.',
    'I am looking at who repeatedly supports which pairings.',
    'One suspicious vote is weaker evidence than a consistent pattern.',
    'A player can have the right conclusion for the wrong reason.',
    'I would rather admit uncertainty than invent certainty.',
    'We can test that theory against later governments.',
    'I do not think volume should decide this discussion.',
    'A claim about unseen cards still depends on the speaker.',
    'I am keeping more than one explanation open.',
    'Let us judge the proposal that is actually on the table.',
    'That argument should still make sense after the next policy.',
    'I am interested in the part we can check publicly.',
    'Trust should have a reason and an expiry date.',
    'We should not punish someone merely for disagreeing.',
    'I am watching whether people apply their standards consistently.',
    'Give me a concrete decision to compare with that claim.',
  ],
} as const;
export type DialogueTopic = keyof typeof DIALOGUE;
